# Generated by Django 5.2.14 on 2026-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile_active_partner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastConnected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('last_user_session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='active_partner_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='active_partner_profession',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_busy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_connected_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('busy', 'Busy')], null=True),
        ),
    ]
