# Generated by Django 5.2.14 on 2026-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_lastconnected_remove_userprofile_active_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', null=True),
        ),
    ]
