# Generated by Django 5.2.14 on 2026-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_connected_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lastconnected',
            name='last_user_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lastconnected',
            name='user_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10, null=True),
        ),
    ]
