# Generated by Django 5.2.14 on 2026-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userprofile_last_connected_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_age_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reconnect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
