# Generated by Django 5.2.14 on 2026-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userprofile_last_reset_date_userprofile_pref_age_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='offline', max_length=10, null=True),
        ),
    ]
